// All the possible language options
//NOTE: Google Translate's supported languages list is taken as the baseline
export const enum LangCode {
  Auto = 'auto',
  Abkhaz = 'ab',
  Acehnese = 'ace',
  Acholi = 'ach',
  Afrikaans = 'af',
  Albanian = 'sq',
  Alur = 'alz',
  Amharic = 'am',
  Arabic = 'ar',
  Armenian = 'hy',
  Assamese = 'as',
  Awadhi = 'awa',
  Aymara = 'ay',
  Azerbaijani = 'az',
  Balinese = 'ban',
  Bambara = 'bm',
  Bashkir = 'ba',
  Basque = 'eu',
  BatakKaro = 'btx',
  BatakSimalungun = 'bts',
  BatakToba = 'bbc',
  Belarusian = 'be',
  Bemba = 'bem',
  Bengali = 'bn',
  Betawi = 'bew',
  Bhojpuri = 'bho',
  Bikol = 'bik',
  Bosnian = 'bs',
  Breton = 'br',
  Bulgarian = 'bg',
  Buryat = 'bua',
  Cantonese = 'yue',
  Catalan = 'ca',
  Cebuano = 'ceb',
  Chichewa = 'ny',
  Chinese = 'zh',
  ChineseSimplified = 'zh-CN',
  ChineseTraditional = 'zh-TW',
  Chuvash = 'cv',
  Corsican = 'co',
  CrimeanTatar = 'crh',
  Croatian = 'hr',
  Czech = 'cs',
  Danish = 'da',
  Dinka = 'din',
  Divehi = 'dv',
  Dogri = 'doi',
  Dombe = 'dov',
  Dutch = 'nl',
  Dzongkha = 'dz',
  English = 'en',
  EnglishBritish = 'en-gb',
  EnglishAmerican = 'en-us',
  Esperanto = 'eo',
  Estonian = 'et',
  Ewe = 'ee',
  Fijian = 'fj',
  Filipino = 'fil',
  Finnish = 'fi',
  French = 'fr',
  FrenchFrance = 'fr-FR',
  FrenchCanadian = 'fr-CA',
  Frisian = 'fy',
  Fulfulde = 'ff',
  Ga = 'gaa',
  Galician = 'gl',
  Ganda = 'lg',
  Georgian = 'ka',
  German = 'de',
  Greek = 'el',
  Guarani = 'gn',
  Gujarati = 'gu',
  HaitianCreole = 'ht',
  HakhaChin = 'cnh',
  Hausa = 'ha',
  Hawaiian = 'haw',
  Hebrew = 'he',
  Hiligaynon = 'hil',
  Hindi = 'hi',
  Hmong = 'hmn',
  Hungarian = 'hu',
  Hunsrik = 'hrx',
  Icelandic = 'is',
  Igbo = 'ig',
  Iloko = 'ilo',
  Indonesian = 'id',
  Irish = 'ga',
  Italian = 'it',
  Japanese = 'ja',
  Javanese = 'jv',
  Kannada = 'kn',
  Kapampangan = 'pam',
  Kazakh = 'kk',
  Khmer = 'km',
  Kiga = 'cgg',
  Kinyarwanda = 'rw',
  Kituba = 'ktu',
  Konkani = 'gom',
  Korean = 'ko',
  Krio = 'kri',
  KurdishKurmanji = 'ku',
  KurdishSorani = 'ckb',
  Kyrgyz = 'ky',
  Lao = 'lo',
  Latgalian = 'ltg',
  Latin = 'la',
  Latvian = 'lv',
  Ligurian = 'lij',
  Limburgan = 'li',
  Lingala = 'ln',
  Lithuanian = 'lt',
  Lombard = 'lmo',
  Luo = 'luo',
  Luxembourgish = 'lb',
  Macedonian = 'mk',
  Maithili = 'mai',
  Makassar = 'mak',
  Malagasy = 'mg',
  Malay = 'ms',
  MalayJawi = 'ms-Arab',
  Malayalam = 'ml',
  Maltese = 'mt',
  Maori = 'mi',
  Marathi = 'mr',
  MeadowMari = 'chm',
  Meiteilon = 'mni-Mtei',
  Minang = 'min',
  Mizo = 'lus',
  Mongolian = 'mn',
  Burmese = 'my',
  NdebeleSouth = 'nr',
  Nepalbhasa = 'new',
  Nepali = 'ne',
  NorthernSotho = 'nso',
  Norwegian = 'no',
  Nuer = 'nus',
  Occitan = 'oc',
  Odia = 'or',
  Oromo = 'om',
  Pangasinan = 'pag',
  Papiamento = 'pap',
  Pashto = 'ps',
  Persian = 'fa',
  Polish = 'pl',
  Portuguese = 'pt',
  PortuguesePortugal = 'pt-PT',
  PortugueseBrazil = 'pt-BR',
  Punjabi = 'pa',
  PunjabiShahmukhi = 'pa-Arab',
  Quechua = 'qu',
  Romani = 'rom',
  Romanian = 'ro',
  Rundi = 'rn',
  Russian = 'ru',
  Samoan = 'sm',
  Sango = 'sg',
  Sanskrit = 'sa',
  ScotsGaelic = 'gd',
  Serbian = 'sr',
  Sesotho = 'st',
  SeychelloisCreole = 'crs',
  Shan = 'shn',
  Shona = 'sn',
  Sicilian = 'scn',
  Silesian = 'szl',
  Sindhi = 'sd',
  Sinhala = 'si',
  Slovak = 'sk',
  Slovenian = 'sl',
  Somali = 'so',
  Spanish = 'es',
  SpanishLatinAmerican = 'es-419',
  Sundanese = 'su',
  Swahili = 'sw',
  Swati = 'ss',
  Swedish = 'sv',
  Tajik = 'tg',
  Tamil = 'ta',
  Tatar = 'tt',
  Telugu = 'te',
  Tetum = 'tet',
  Thai = 'th',
  Tigrinya = 'ti',
  Tsonga = 'ts',
  Tswana = 'tn',
  Turkish = 'tr',
  Turkmen = 'tk',
  Twi = 'ak',
  Ukrainian = 'uk',
  Urdu = 'ur',
  Uyghur = 'ug',
  Uzbek = 'uz',
  Vietnamese = 'vi',
  Welsh = 'cy',
  Xhosa = 'xh',
  Yiddish = 'yi',
  Yoruba = 'yo',
  YucatecMaya = 'yua',
  Zulu = 'zu',
}

// List of pretty names to use in UI
export const LANGUAGE_REGISTRY: Record<LangCode, string> = {
  [LangCode.Auto]: 'Auto-detect',
  [LangCode.Abkhaz]: 'Abkhaz',
  [LangCode.Acehnese]: 'Acehnese',
  [LangCode.Acholi]: 'Acholi',
  [LangCode.Afrikaans]: 'Afrikaans',
  [LangCode.Albanian]: 'Albanian',
  [LangCode.Alur]: 'Alur',
  [LangCode.Amharic]: 'Amharic',
  [LangCode.Arabic]: 'Arabic',
  [LangCode.Armenian]: 'Armenian',
  [LangCode.Assamese]: 'Assamese',
  [LangCode.Awadhi]: 'Awadhi',
  [LangCode.Aymara]: 'Aymara',
  [LangCode.Azerbaijani]: 'Azerbaijani',
  [LangCode.Balinese]: 'Balinese',
  [LangCode.Bambara]: 'Bambara',
  [LangCode.Bashkir]: 'Bashkir',
  [LangCode.Basque]: 'Basque',
  [LangCode.BatakKaro]: 'Batak Karo',
  [LangCode.BatakSimalungun]: 'Batak Simalungun',
  [LangCode.BatakToba]: 'Batak Toba',
  [LangCode.Belarusian]: 'Belarusian',
  [LangCode.Bemba]: 'Bemba',
  [LangCode.Bengali]: 'Bengali',
  [LangCode.Betawi]: 'Betawi',
  [LangCode.Bhojpuri]: 'Bhojpuri',
  [LangCode.Bikol]: 'Bikol',
  [LangCode.Bosnian]: 'Bosnian',
  [LangCode.Breton]: 'Breton',
  [LangCode.Bulgarian]: 'Bulgarian',
  [LangCode.Buryat]: 'Buryat',
  [LangCode.Cantonese]: 'Cantonese',
  [LangCode.Catalan]: 'Catalan',
  [LangCode.Cebuano]: 'Cebuano',
  [LangCode.Chichewa]: 'Chichewa',
  [LangCode.Chinese]: 'Chinese',
  [LangCode.ChineseSimplified]: 'Chinese (Simplified)',
  [LangCode.ChineseTraditional]: 'Chinese (Traditional)',
  [LangCode.Chuvash]: 'Chuvash',
  [LangCode.Corsican]: 'Corsican',
  [LangCode.CrimeanTatar]: 'Crimean Tatar',
  [LangCode.Croatian]: 'Croatian',
  [LangCode.Czech]: 'Czech',
  [LangCode.Danish]: 'Danish',
  [LangCode.Dinka]: 'Dinka',
  [LangCode.Divehi]: 'Divehi',
  [LangCode.Dogri]: 'Dogri',
  [LangCode.Dombe]: 'Dombe',
  [LangCode.Dutch]: 'Dutch',
  [LangCode.Dzongkha]: 'Dzongkha',
  [LangCode.English]: 'English',
  [LangCode.EnglishBritish]: 'English (British)',
  [LangCode.EnglishAmerican]: 'English (American)',
  [LangCode.Esperanto]: 'Esperanto',
  [LangCode.Estonian]: 'Estonian',
  [LangCode.Ewe]: 'Ewe',
  [LangCode.Fijian]: 'Fijian',
  [LangCode.Filipino]: 'Filipino',
  [LangCode.Finnish]: 'Finnish',
  [LangCode.French]: 'French',
  [LangCode.FrenchFrance]: 'French (France)',
  [LangCode.FrenchCanadian]: 'French (Canada)',
  [LangCode.Frisian]: 'Frisian',
  [LangCode.Fulfulde]: 'Fulfulde',
  [LangCode.Ga]: 'Ga',
  [LangCode.Galician]: 'Galician',
  [LangCode.Ganda]: 'Ganda',
  [LangCode.Georgian]: 'Georgian',
  [LangCode.German]: 'German',
  [LangCode.Greek]: 'Greek',
  [LangCode.Guarani]: 'Guarani',
  [LangCode.Gujarati]: 'Gujarati',
  [LangCode.HaitianCreole]: 'Haitian Creole',
  [LangCode.HakhaChin]: 'Hakha Chin',
  [LangCode.Hausa]: 'Hausa',
  [LangCode.Hawaiian]: 'Hawaiian',
  [LangCode.Hebrew]: 'Hebrew',
  [LangCode.Hiligaynon]: 'Hiligaynon',
  [LangCode.Hindi]: 'Hindi',
  [LangCode.Hmong]: 'Hmong',
  [LangCode.Hungarian]: 'Hungarian',
  [LangCode.Hunsrik]: 'Hunsrik',
  [LangCode.Icelandic]: 'Icelandic',
  [LangCode.Igbo]: 'Igbo',
  [LangCode.Iloko]: 'Iloko',
  [LangCode.Indonesian]: 'Indonesian',
  [LangCode.Irish]: 'Irish',
  [LangCode.Italian]: 'Italian',
  [LangCode.Japanese]: 'Japanese',
  [LangCode.Javanese]: 'Javanese',
  [LangCode.Kannada]: 'Kannada',
  [LangCode.Kapampangan]: 'Kapampangan',
  [LangCode.Kazakh]: 'Kazakh',
  [LangCode.Khmer]: 'Khmer',
  [LangCode.Kiga]: 'Kiga',
  [LangCode.Kinyarwanda]: 'Kinyarwanda',
  [LangCode.Kituba]: 'Kituba',
  [LangCode.Konkani]: 'Konkani',
  [LangCode.Korean]: 'Korean',
  [LangCode.Krio]: 'Krio',
  [LangCode.KurdishKurmanji]: 'Kurdish (Kurmanji)',
  [LangCode.KurdishSorani]: 'Kurdish (Sorani)',
  [LangCode.Kyrgyz]: 'Kyrgyz',
  [LangCode.Lao]: 'Lao',
  [LangCode.Latgalian]: 'Latgalian',
  [LangCode.Latin]: 'Latin',
  [LangCode.Latvian]: 'Latvian',
  [LangCode.Ligurian]: 'Ligurian',
  [LangCode.Limburgan]: 'Limburgan',
  [LangCode.Lingala]: 'Lingala',
  [LangCode.Lithuanian]: 'Lithuanian',
  [LangCode.Lombard]: 'Lombard',
  [LangCode.Luo]: 'Luo',
  [LangCode.Luxembourgish]: 'Luxembourgish',
  [LangCode.Macedonian]: 'Macedonian',
  [LangCode.Maithili]: 'Maithili',
  [LangCode.Makassar]: 'Makassar',
  [LangCode.Malagasy]: 'Malagasy',
  [LangCode.Malay]: 'Malay',
  [LangCode.MalayJawi]: 'Malay (Jawi)',
  [LangCode.Malayalam]: 'Malayalam',
  [LangCode.Maltese]: 'Maltese',
  [LangCode.Maori]: 'Maori',
  [LangCode.Marathi]: 'Marathi',
  [LangCode.MeadowMari]: 'Meadow Mari',
  [LangCode.Meiteilon]: 'Meiteilon (Manipuri)',
  [LangCode.Minang]: 'Minangkabau',
  [LangCode.Mizo]: 'Mizo',
  [LangCode.Mongolian]: 'Mongolian',
  [LangCode.Burmese]: 'Burmese',
  [LangCode.NdebeleSouth]: 'South Ndebele',
  [LangCode.Nepalbhasa]: 'Nepal Bhasa',
  [LangCode.Nepali]: 'Nepali',
  [LangCode.NorthernSotho]: 'Northern Sotho',
  [LangCode.Norwegian]: 'Norwegian',
  [LangCode.Nuer]: 'Nuer',
  [LangCode.Occitan]: 'Occitan',
  [LangCode.Odia]: 'Odia',
  [LangCode.Oromo]: 'Oromo',
  [LangCode.Pangasinan]: 'Pangasinan',
  [LangCode.Papiamento]: 'Papiamento',
  [LangCode.Pashto]: 'Pashto',
  [LangCode.Persian]: 'Persian',
  [LangCode.Polish]: 'Polish',
  [LangCode.Portuguese]: 'Portuguese',
  [LangCode.PortuguesePortugal]: 'Portuguese (Portugal)',
  [LangCode.PortugueseBrazil]: 'Portuguese (Brazil)',
  [LangCode.Punjabi]: 'Punjabi',
  [LangCode.PunjabiShahmukhi]: 'Punjabi (Shahmukhi)',
  [LangCode.Quechua]: 'Quechua',
  [LangCode.Romani]: 'Romani',
  [LangCode.Romanian]: 'Romanian',
  [LangCode.Rundi]: 'Rundi',
  [LangCode.Russian]: 'Russian',
  [LangCode.Samoan]: 'Samoan',
  [LangCode.Sango]: 'Sango',
  [LangCode.Sanskrit]: 'Sanskrit',
  [LangCode.ScotsGaelic]: 'Scots Gaelic',
  [LangCode.Serbian]: 'Serbian',
  [LangCode.Sesotho]: 'Sesotho',
  [LangCode.SeychelloisCreole]: 'Seychellois Creole',
  [LangCode.Shan]: 'Shan',
  [LangCode.Shona]: 'Shona',
  [LangCode.Sicilian]: 'Sicilian',
  [LangCode.Silesian]: 'Silesian',
  [LangCode.Sindhi]: 'Sindhi',
  [LangCode.Sinhala]: 'Sinhala',
  [LangCode.Slovak]: 'Slovak',
  [LangCode.Slovenian]: 'Slovenian',
  [LangCode.Somali]: 'Somali',
  [LangCode.Spanish]: 'Spanish',
  [LangCode.SpanishLatinAmerican]: '"Spanish (Latin American)',
  [LangCode.Sundanese]: 'Sundanese',
  [LangCode.Swahili]: 'Swahili',
  [LangCode.Swati]: 'Swati',
  [LangCode.Swedish]: 'Swedish',
  [LangCode.Tajik]: 'Tajik',
  [LangCode.Tamil]: 'Tamil',
  [LangCode.Tatar]: 'Tatar',
  [LangCode.Telugu]: 'Telugu',
  [LangCode.Tetum]: 'Tetum',
  [LangCode.Thai]: 'Thai',
  [LangCode.Tigrinya]: 'Tigrinya',
  [LangCode.Tsonga]: 'Tsonga',
  [LangCode.Tswana]: 'Tswana',
  [LangCode.Turkish]: 'Turkish',
  [LangCode.Turkmen]: 'Turkmen',
  [LangCode.Twi]: 'Twi',
  [LangCode.Ukrainian]: 'Ukrainian',
  [LangCode.Urdu]: 'Urdu',
  [LangCode.Uyghur]: 'Uyghur',
  [LangCode.Uzbek]: 'Uzbek',
  [LangCode.Vietnamese]: 'Vietnamese',
  [LangCode.Welsh]: 'Welsh',
  [LangCode.Xhosa]: 'Xhosa',
  [LangCode.Yiddish]: 'Yiddish',
  [LangCode.Yoruba]: 'Yoruba',
  [LangCode.YucatecMaya]: 'Yucatec Maya',
  [LangCode.Zulu]: 'Zulu',
};
