import * as Tesseract from 'tesseract.js';
import { Lang } from './languages';

export async function runOCR(element: Element | string, langs?: string): Promise<string> {
  if (element instanceof HTMLImageElement || typeof element === 'string') {
    const result = await Tesseract.recognize(element, langs);
    return result.data.text;
  }
  throw new Error('Target is not an image element');
}

export const SupportedLangs: Lang[] = [
  { key: 'afr', text: 'Afrikaans' },
  { key: 'amh', text: 'Amharic' },
  { key: 'ara', text: 'Arabic' },
  { key: 'asm', text: 'Assamese' },
  { key: 'aze', text: 'Azerbaijani' },
  { key: 'aze_cyrl', text: 'Azerbaijani - Cyrillic' },
  { key: 'bel', text: 'Belarusian' },
  { key: 'ben', text: 'Bengali' },
  { key: 'bod', text: 'Tibetan' },
  { key: 'bos', text: 'Bosnian' },
  { key: 'bul', text: 'Bulgarian' },
  { key: 'cat', text: 'Catalan; Valencian' },
  { key: 'ceb', text: 'Cebuano' },
  { key: 'ces', text: 'Czech' },
  { key: 'chi_sim', text: 'Chinese - Simplified' },
  { key: 'chi_tra', text: 'Chinese - Traditional' },
  { key: 'chr', text: 'Cherokee' },
  { key: 'cym', text: 'Welsh' },
  { key: 'dan', text: 'Danish' },
  { key: 'deu', text: 'German' },
  { key: 'dzo', text: 'Dzongkha' },
  { key: 'ell', text: 'Greek, Modern (1453-)' },
  { key: 'eng', text: 'English' },
  { key: 'enm', text: 'English, Middle (1100-1500)' },
  { key: 'epo', text: 'Esperanto' },
  { key: 'est', text: 'Estonian' },
  { key: 'eus', text: 'Basque' },
  { key: 'fas', text: 'Persian' },
  { key: 'fin', text: 'Finnish' },
  { key: 'fra', text: 'French' },
  { key: 'frk', text: 'German Fraktur' },
  { key: 'frm', text: 'French, Middle (ca. 1400-1600)' },
  { key: 'gle', text: 'Irish' },
  { key: 'glg', text: 'Galician' },
  { key: 'grc', text: 'Greek, Ancient (-1453)' },
  { key: 'guj', text: 'Gujarati' },
  { key: 'hat', text: 'Haitian; Haitian Creole' },
  { key: 'heb', text: 'Hebrew' },
  { key: 'hin', text: 'Hindi' },
  { key: 'hrv', text: 'Croatian' },
  { key: 'hun', text: 'Hungarian' },
  { key: 'iku', text: 'Inuktitut' },
  { key: 'ind', text: 'Indonesian' },
  { key: 'isl', text: 'Icelandic' },
  { key: 'ita', text: 'Italian' },
  { key: 'ita_old', text: 'Italian - Old' },
  { key: 'jav', text: 'Javanese' },
  { key: 'jpn', text: 'Japanese' },
  { key: 'kan', text: 'Kannada' },
  { key: 'kat', text: 'Georgian' },
  { key: 'kat_old', text: 'Georgian - Old' },
  { key: 'kaz', text: 'Kazakh' },
  { key: 'khm', text: 'Central Khmer' },
  { key: 'kir', text: 'Kirghiz; Kyrgyz' },
  { key: 'kor', text: 'Korean' },
  { key: 'kur', text: 'Kurdish' },
  { key: 'lao', text: 'Lao' },
  { key: 'lat', text: 'Latin' },
  { key: 'lav', text: 'Latvian' },
  { key: 'lit', text: 'Lithuanian' },
  { key: 'mal', text: 'Malayalam' },
  { key: 'mar', text: 'Marathi' },
  { key: 'mkd', text: 'Macedonian' },
  { key: 'mlt', text: 'Maltese' },
  { key: 'msa', text: 'Malay' },
  { key: 'mya', text: 'Burmese' },
  { key: 'nep', text: 'Nepali' },
  { key: 'nld', text: 'Dutch; Flemish' },
  { key: 'nor', text: 'Norwegian' },
  { key: 'ori', text: 'Oriya' },
  { key: 'pan', text: 'Panjabi; Punjabi' },
  { key: 'pol', text: 'Polish' },
  { key: 'por', text: 'Portuguese' },
  { key: 'pus', text: 'Pushto; Pashto' },
  { key: 'ron', text: 'Romanian; Moldavian; Moldovan' },
  { key: 'rus', text: 'Russian' },
  { key: 'san', text: 'Sanskrit' },
  { key: 'sin', text: 'Sinhala; Sinhalese' },
  { key: 'slk', text: 'Slovak' },
  { key: 'slv', text: 'Slovenian' },
  { key: 'spa', text: 'Spanish; Castilian' },
  { key: 'spa_old', text: 'Spanish; Castilian - Old' },
  { key: 'sqi', text: 'Albanian' },
  { key: 'srp', text: 'Serbian' },
  { key: 'srp_latn', text: 'Serbian - Latin' },
  { key: 'swa', text: 'Swahili' },
  { key: 'swe', text: 'Swedish' },
  { key: 'syr', text: 'Syriac' },
  { key: 'tam', text: 'Tamil' },
  { key: 'tel', text: 'Telugu' },
  { key: 'tgk', text: 'Tajik' },
  { key: 'tgl', text: 'Tagalog' },
  { key: 'tha', text: 'Thai' },
  { key: 'tir', text: 'Tigrinya' },
  { key: 'tur', text: 'Turkish' },
  { key: 'uig', text: 'Uighur; Uyghur' },
  { key: 'ukr', text: 'Ukrainian' },
  { key: 'urd', text: 'Urdu' },
  { key: 'uzb', text: 'Uzbek' },
  { key: 'uzb_cyrl', text: 'Uzbek - Cyrillic' },
  { key: 'vie', text: 'Vietnamese' },
  { key: 'yid', text: 'Yiddish' },
];
