import * as Tesseract from 'tesseract.js';
import { LangCode } from './languages';

export async function runOCR(element: Element | string, ...langs: LangCode[]): Promise<string> {
  if (element instanceof HTMLImageElement || typeof element === 'string') {
    const langsString = langs.map((l) => TESSERACT_LANGS[l]).join('+') || 'eng';
    const result = await Tesseract.recognize(element, langsString);
    return result.data.text;
  }
  throw new Error('Target is not an image element');
}

const TESSERACT_LANGS: Partial<Record<LangCode, string>> = {
  [LangCode.Afrikaans]: 'afr',
  [LangCode.Albanian]: 'sqi',
  [LangCode.Amharic]: 'amh',
  [LangCode.Arabic]: 'ara',
  [LangCode.Armenian]: 'hye',
  [LangCode.Azerbaijani]: 'aze',
  [LangCode.Basque]: 'eus',
  [LangCode.Belarusian]: 'bel',
  [LangCode.Bengali]: 'ben',
  [LangCode.Bosnian]: 'bos',
  [LangCode.Bulgarian]: 'bul',
  [LangCode.Burmese]: 'mya',
  [LangCode.Catalan]: 'cat',
  [LangCode.Cebuano]: 'ceb',
  [LangCode.Czech]: 'ces',
  [LangCode.Danish]: 'dan',
  [LangCode.Dutch]: 'nld',
  [LangCode.English]: 'eng',
  [LangCode.Estonian]: 'est',
  [LangCode.Filipino]: 'tgl',
  [LangCode.Finnish]: 'fin',
  [LangCode.French]: 'fra',
  [LangCode.FrenchCanadian]: 'fra',
  [LangCode.Frisian]: 'fry',
  [LangCode.Galician]: 'glg',
  [LangCode.Georgian]: 'kat',
  [LangCode.German]: 'deu',
  [LangCode.Greek]: 'ell',
  [LangCode.Guarani]: 'grn',
  [LangCode.Gujarati]: 'guj',
  [LangCode.Hebrew]: 'heb',
  [LangCode.Hindi]: 'hin',
  [LangCode.Hungarian]: 'hun',
  [LangCode.Icelandic]: 'isl',
  [LangCode.Indonesian]: 'ind',
  [LangCode.Irish]: 'gle',
  [LangCode.Italian]: 'ita',
  [LangCode.Japanese]: 'jpn',
  [LangCode.Javanese]: 'jav',
  [LangCode.Kannada]: 'kan',
  [LangCode.Kazakh]: 'kaz',
  [LangCode.Khmer]: 'khm',
  [LangCode.Korean]: 'kor',
  [LangCode.Kyrgyz]: 'kir',
  [LangCode.Lao]: 'lao',
  [LangCode.Latin]: 'lat',
  [LangCode.Latvian]: 'lav',
  [LangCode.Lithuanian]: 'lit',
  [LangCode.Macedonian]: 'mkd',
  [LangCode.Malay]: 'msa',
  [LangCode.Malayalam]: 'mal',
  [LangCode.Maltese]: 'mlt',
  [LangCode.Marathi]: 'mar',
  [LangCode.Nepali]: 'nep',
  [LangCode.Norwegian]: 'nor',
  [LangCode.Odia]: 'ori',
  [LangCode.Persian]: 'fas',
  [LangCode.Polish]: 'pol',
  [LangCode.Portuguese]: 'por',
  [LangCode.PortugueseBrazil]: 'por',
  [LangCode.PortuguesePortugal]: 'por',
  [LangCode.Punjabi]: 'pan',
  [LangCode.Romanian]: 'ron',
  [LangCode.Russian]: 'rus',
  [LangCode.Sanskrit]: 'san',
  [LangCode.Serbian]: 'srp',
  [LangCode.Slovak]: 'slk',
  [LangCode.Slovenian]: 'slv',
  [LangCode.Spanish]: 'spa',
  [LangCode.Swahili]: 'swa',
  [LangCode.Swedish]: 'swe',
  [LangCode.Tamil]: 'tam',
  [LangCode.Telugu]: 'tel',
  [LangCode.Thai]: 'tha',
  [LangCode.Tajik]: 'tgk',
  [LangCode.Turkish]: 'tur',
  [LangCode.Ukrainian]: 'ukr',
  [LangCode.Urdu]: 'urd',
  [LangCode.Uzbek]: 'uzb',
  [LangCode.Vietnamese]: 'vie',
  [LangCode.Welsh]: 'cym',
  [LangCode.Yiddish]: 'yid',
  [LangCode.Zulu]: 'zul',
};

export const OCR_LANGS = new Set<LangCode>(Object.keys(TESSERACT_LANGS) as LangCode[]);
